/gate/source/addSource mybeam gps
/gate/source/mybeam/gps/particle       proton
/gate/source/mybeam/gps/ene/mono       200 MeV
/gate/source/mybeam/gps/ene/type       Mono
#/gate/source/mybeam/gps/ene/type       Gauss
#/gate/source/mybeam/gps/ene/sigma      0.5 MeV
/gate/source/mybeam/gps/pos/halfx      8 mm
/gate/source/mybeam/gps/pos/halfy      1 mm
/gate/source/mybeam/gps/pos/centre     1060 0 0 mm
/gate/source/mybeam/gps/pos/rot1       0 1 0
/gate/source/mybeam/gps/pos/rot2       0 0 1
/gate/source/mybeam/gps/pos/type       Plane
/gate/source/mybeam/gps/pos/shape      Rectangle
/gate/source/mybeam/gps/direction      -1 0 0
/gate/source/mybeam/gps/ang/type       focused
/gate/source/mybeam/gps/ang/rot1       0 1 0
/gate/source/mybeam/gps/ang/rot2       0 0 1
/gate/source/mybeam/gps/ang/focuspoint 1000 0 0 mm

