# WaterSph
/gate/world/daughters/name                     WaterSph
/gate/world/daughters/insert                   sphere
/gate/WaterSph/placement/setTranslation        100 0 0 cm
/gate/WaterSph/geometry/setRmin                90 cm
/gate/WaterSph/geometry/setRmax                110 cm
/gate/WaterSph/setMaterial                     Water
/gate/WaterSph/vis/setVisible 0
/gate/WaterSph/vis/setColor blue

# BoneInsert1
/gate/WaterSph/daughters/name                  BoneInsert1
/gate/WaterSph/daughters/insert                sphere
/gate/BoneInsert1/placement/setTranslation     0 0 0 cm
/gate/BoneInsert1/geometry/setRmin             90 cm
/gate/BoneInsert1/geometry/setRmax             92 cm
/gate/BoneInsert1/geometry/setThetaStart       88 deg
/gate/BoneInsert1/geometry/setDeltaTheta       4 deg
/gate/BoneInsert1/geometry/setPhiStart         175 deg
/gate/BoneInsert1/geometry/setDeltaPhi         2 deg
/gate/BoneInsert1/setMaterial                  SpineBone
/gate/WaterSph/vis/setVisible 1
/gate/WaterSph/vis/setColor white

# BoneInsert2
/gate/WaterSph/daughters/name                  BoneInsert2
/gate/WaterSph/daughters/insert                sphere
/gate/BoneInsert2/placement/setTranslation     0 0 0 cm
/gate/BoneInsert2/geometry/setRmin             99 cm
/gate/BoneInsert2/geometry/setRmax             101 cm
/gate/BoneInsert2/geometry/setThetaStart       88 deg
/gate/BoneInsert2/geometry/setDeltaTheta       4 deg
/gate/BoneInsert2/geometry/setPhiStart         179 deg
/gate/BoneInsert2/geometry/setDeltaPhi         2 deg
/gate/BoneInsert2/setMaterial                  SpineBone
/gate/WaterSph/vis/setVisible 1
/gate/WaterSph/vis/setColor white

# BoneInsert3
/gate/WaterSph/daughters/name                  BoneInsert3
/gate/WaterSph/daughters/insert                sphere
/gate/BoneInsert3/placement/setTranslation     0 0 0 cm
/gate/BoneInsert3/geometry/setRmin             108 cm
/gate/BoneInsert3/geometry/setRmax             110 cm
/gate/BoneInsert3/geometry/setThetaStart       88 deg
/gate/BoneInsert3/geometry/setDeltaTheta       4 deg
/gate/BoneInsert3/geometry/setPhiStart         183 deg
/gate/BoneInsert3/geometry/setDeltaPhi         2 deg
/gate/BoneInsert3/setMaterial                  SpineBone
/gate/BoneInsert3/vis/setVisible 1
/gate/BoneInsert3/vis/setColor white

